# Generated by Django 3.1.6 on 2021-02-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='text',
        ),
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
